*Figure4_Median_OOP_Expenses.sas;
options nosource nodate nonumber nonotes nocenter;
LIBNAME new "U:\_Flu\SDS";
ods listing;
ods graphics off;
ods select domain domainquantiles;
title 'Figure 4A (Median out-of-pocket expenses for all care services)';
proc surveymeans data=new.person15_16 Nobs median;
stratum varstr;
cluster varpsu;
weight perwtf;
var  g_AL_self_family ;
domain flu('1') flu('1');
run;
options nosource nodate nonumber nonotes nocenter;
LIBNAME new "U:\_Flu\SDS";
ods listing;
ods graphics off;
ods select domain domainquantiles;
title 'Figure 4B (Median out-of-pocket expenses for ambulatory care with an ambulatory visit)';
proc surveymeans data=new.person16_17 Nobs median;
stratum varstr;
cluster varpsu;
weight perwtf_16_17;
var  g_AM_self_family ;
domain flu('1')*max_ob_op('1') ;
run;

options nosource nodate nonumber nonotes nocenter;
LIBNAME new "U:\_Flu\SDS";
ods listing;
ods graphics off;
ods select domain domainquantiles;
title 'Figure 4C (Median out-of-pocket expenses for prescribed medicines with a prescription fill)';
proc surveymeans data=new.person16_17 Nobs median;
stratum varstr;
cluster varpsu;
weight perwtf_16_17;
var  g_RX_self_family ;
domain flu('1')*max_RX('1');
run;

options nosource nodate nonumber nonotes nocenter;
LIBNAME new "U:\_Flu\SDS";
ods listing;
ods graphics off;
ods select domain domainquantiles;
title 'Figure 4D (Median out-of-pocket expenses for emergency care with an ER visit)';
proc surveymeans data=new.person16_17 Nobs median;
stratum varstr;
cluster varpsu;
weight perwtf_16_17;
var  g_ER_self_family ;
domain flu('1')*max_ER('1');
run;
